# Generated by Django 4.1.1 on 2022-10-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
